version: "3.7"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./src:/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: chialab/php:7.3-fpm
    volumes:
      - ./src:/src
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: "typer"
      MYSQL_USER: "mysql"
      MYSQL_ROOT_PASSWORD: "amogus"
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
